### ISSUE TITLE
Config files point to wrong "datacenter"

### ISSUE THREAD

**Issue by akundrockTechtonic** [aws-samples/aws-sigv4-auth-cassandra-java-driver-examples#4]
Hello, 
I was following a tutorial for the Managed Cassandra Service and found this repo from this link.
[MCS Example](https://docs.aws.amazon.com/mcs/latest/devguide/security_iam_id-based-policy-examples.html)

After building the .jar file and running the command
`java -Djavax.net.ssl.trustStore=./cassandra_truststore.jks            -Djavax.net.ssl.trustStorePassword=amazon -jar aws-sigv4-auth-cassandra-java-driver-examples-1.0.1.jar us-west-2 cassandra.us-west-2.amazonaws.com 1234`

I receive the error: `Exception in thread "main" com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query`

To fix this, I had to edit `src/main/resources/application-full.conf` and `src/main/resources/application.conf` `local-datacenter =us-east-2` (or your prefered region)

After rebuilding the JAR I was able to get the example working.

Recommend revisiting the local-datacenter field as that seems to have changed.

Thanks for posting this code and the original guide!

**Comment by dchenbec** [comment]
Thanks, we'll take a look.

**Comment by dchenbec** [comment]
This should be addressed with the change in bb5d6374a77a5901ef9660cf87da1d9aed285269. Please let us know if you see any further difficulties.

**Comment by Vaishnav-puram** [comment]
please review my issue :
https://stackoverflow.com/questions/75307194/not-able-to-connect-to-cassandra-from-my-spring-boot-application-throwing-exce

**Comment by Vaishnav-puram** [comment]
please review my issue :
https://stackoverflow.com/questions/75307194/not-able-to-connect-to-cassandra-from-my-spring-boot-application-throwing-exce
